project:
  type: book
  output-dir: docs

book:
  title: "Blog_Arthur"
  author: "Arthur"
  # date: "4/16/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - Bloomberg_HQ.qmd
    - London.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
    # textures.css
        light: [cerulean, flatly]
        dark: [cerulean, darkly]
  pdf:
    documentclass: scrreprt

editor: visual

