project:
  type: book

book:
  title: "Blog_BigA"
  author: "Big A"
  date: "4/16/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - Bloomberg_HQ.qmd
    - summary.qmd
    - London.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

