<div style="text-align: justify">

# Bloomberg HQ; The Globalised Green Jewel of a perhaps Bygone Age

The strangely silent Davos convention of 2022 conveyed through its strange lack of attendance that the time of Globalisation was maybe coming to an end. The Covid years and war in Ukraine had sapped any hope of recovering the confidence, hope and dynamism that represented this yearly celebration of globalisation and the dream of a "Flat World" as the New York Times once coined where peace, prosperity, democracy and commerce we're the insurmountable future of humanity.

Turning our eyes to the European HQ of Bloomberg, a point of comparison seems fit to analyse. Inaugurated in 2017, this building is to me a product of a world that is most likely coming to a close. Epitomising 21st century internet globalisation and pre-covid time: the Bloomberg HQ can be seen when confronted to the current world news knowing the international sourcing of its skills, materials and ideas like a physical anachronism.

To consider this building to be out of date and disconnected with reality would be however quite unfair as its essence still detain definite awe-inspiring details. Looking for example at the awareness of its historic environment , whether that be through the elaboration of the Bloomberg Arcade recovering a lost portion of Watling Street (an important Roman road) back to the city grid or even more spectacularly the construction of an antiquity museum surrounding the archeological site of the temple of Mithras sitting under the new Bloomberg HQ, it is clear that great research has been undertook to reveal and protect the built heritage surrounding these offices. Furthermore, the sustainability ideas and innovations designed for the building can definitely be considered as ground breaking having for example received a BREEAM Outstanding rating and the highest design-stage BREEAM score ever achieved by any major office development in the world in 2017.

Its globalised nature is what will be at the heart of this discussion, regardless of how sustainable and aesthetically pleasing this stone structure is, it must not distract from the fact that the way it has been built is fundamentally based on the development of a globalised trading and commercial network that enabled the gathering of a global pool of ressources, intellect and man power which currently may come to disappear. In a video documenting the elaboration process of this building published by Bloomberg media, we get to understand that firms specialising in different areas of the building we're solicited from around the world. From Japanese bronze making craftsmen making special shading fins that will be placed on the window panes, to a technical glass manufacturing company in China which sent some test samples to Germany for impact testing or stone cutting specialists executed in Italy with marbles from the UK the whole process from design, to manufacturing and building was an endeavour of gigantic proportion that could've only be done through the intense network of commercial activity established throughout the post "Cold War" age.

With rising global political tensions altering the current geopolitical order, international collaboration in craftsmanship may come to be a way of design and building that comes in the time of interregnum something of an anomaly.

## What could this mean for the future of Architecture and Urban Design?

The current shifting of the geopolitical landscape will undeniably have enormous impact on all societies and by extent detain repercussions on Urban design. In the gradual turn to a more fragmented world, the elaboration of buildings sourced by the immense pool of humanity will evidently become more difficult. This deceleration of international commercial interaction could translate in the evolution of building design with a "re-territorialisation" of craftsmanship and sourcing of building material.

Implementation of a circular economy and imposition of tariffs particularly in ever more isolated societies such as China could lead to skills and craftsmanship suddenly becoming an instrument of national security getting subjected to protectionist policies inhibiting it to be exported to other regions of the world. Of course, this won't mean that building design will return to regional determination but limited access to far away craftsmanship could bring about a popularisation of nearer opportunities and an appreciation for skills and knowledge otherwise dismissed as deemed not exotic or special enough, preference will be given to proximity and less to purposeness.

Ironically, the sustainability side of the Bloomberg project boasted its use of nationally sourced materials and workforce something that evidently fits well with the projected future of a more territorially locked design. It would be however misleading to believe this sort of building as representative of what is to come and what is happening on a large scale considering the amount of distance materials and information had to travel in order to build the headquarters.

Injecting geopolitical thinking when reflecting on the future of building design seems unconventional to say the least, the two disciplines have not much in common yet the reality that we are all confronted makes international relations become more salient in our day to day lives. From the products offered on Sainsbury's shelves to the light reflected on the window panes of the Bloomberg HQ, our material surroundings are constantly dependent on the larger geopolitical state of our world. Something that should be kept in mind for any urbanist thinking about the future of cities.
