<div style="text-align: justify">

# Introduction

## Inquiry on the Life of Urban Dwellers in the Anthropocene: To become Earthling in the Urban Age

Fundamentally inspired by the work of Philosopher, Sociologist and Anthropologist Bruno Latour, this small project has the ambition to continue the anthropological study of the moderns through their habitat and built environment.

It is my belief that analysing our societies and culture adapting to the growing challenge of climate change can be seen through the alteration of the urban fabric. The change discovered in the built environment is to me the most telling witness of our struggle to imagine a world where the human footprint is in accordance with Earth's biological processes. An insoluble question surrounds constantly our daily life: How to keep our shared urban way of living while finding sustainable solutions to the climate crisis, as writer Amitav Gosh states: "the ecological crisis is first and foremost a culture one". The entrance of climate into our culture is an event that we have yet to represent and make sense of confirming the current struggle planners and architects are grappling with. Indeed, how do we recreate a built environment for urban dwellers which considers the new critical condition: keeping the habitability of the Earth as the utmost priority and cardinal point of any future housing and planning project. With the projected number of half the human population living in cities by 2050 with some theorists declaring our time as the Urban Age, the way we build and sustain these areas will become central in our fight for climate.

In the soon to become classic contemporary historical work from historian Dipesh Chakrabarty: "The Climate of History in a Planetary Age" building on the Anthropocene theory (Idea that Humanity has become the main actor in the geological processes of Earth) explains thoroughly that the confluence of human history with geological history has altered in a fundamental way the human condition. Today and for the coming years and centuries, humanity will have to contend (because of its sheer size and the ensemble of technical networking sustaining its life on Earth) with the struggle to keep in check the habitability of possible life for humans on Earth. This new responsibility is yet to be fully integrated into our societies and even less into our own individual being but will manifest more of itself only exponentially in the future.

This platform will be dedicated to these reflections through the urban fabric where a simple earthling tries to figure out the complex relationship between urban life and the effects of climate change. By writing any insights, reflections, images, maps, etc... My hope is to better understand how urban dwelling can adapt successfully to the Anthropocene and get by the end a better picture of how we've come to this position and where to go from now, building a liveable city in the Anthropocene. The object of study will be my neighbourhood, Elephant and Castle and its surroundings since the starting point of every research is an appreciation of the physical, sociocultural and microclimatic characteristics of each unique place, understanding that a truly sustainable development emerges from working with the specific characteristics of each location. Furthermore, local study of my neighbourhood will hopefully bring out more insights and specific information about urban dwelling. Developing a caring relationship with our built environment can only bolster ideas, concepts and plans for the city of the future. It is in these kinds of endeavours I believe that we will be able to find the small nuggets of a new ecological imaginary and present a novel way to build, live and think about the city.
